apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-ns
#- analysistemplate.yaml
#- backend/rollout.yaml
#- backend/autoscaler.yaml
resources:
- configmap.yaml
- sealedsecret.yaml
- postgres/statefulset.yaml
- backend/service.yaml
- backend/deployment.yaml
- ingress.yaml
- frontend/service.yaml
- frontend/deployment.yaml
- broadcaster/deployment.yaml
- persistentvolumeclaim.yaml
- persistentvolume.yaml

images:
- name: BACKEND/IMAGE
  newName: yumol/backend
  newTag: 37237213f535acf7227ff53ca054578a05cf471e
- name: BROADCASTER/IMAGE
  newName: yumol/broadcaster
  newTag: 37237213f535acf7227ff53ca054578a05cf471e
- name: FRONTEND/IMAGE
  newName: yumol/frontend
  newTag: 37237213f535acf7227ff53ca054578a05cf471e
- name: POSTGRES/IMAGE
  newName: postgres:13.0
