apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-claim
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: ""
  # volumeName: fileserver
  resources:
    requests:
      storage: 0.2Gi