apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pingpong-ingress
  # annotations:
  #   use "/pingpong" path whilst the ping-pong application listens on "/"
  #   traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
spec:
  rules:
  - http:
      paths:
      - path: /pingpong
        backend:
          serviceName: pingpong-svc
          servicePort: 80
      - path: /
        backend:
          serviceName: main-svc
          servicePort: 80